# Generated by Django 3.0.5 on 2020-04-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='room',
        ),
    ]
