# Generated by Django 3.0.5 on 2020-04-18 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_player_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='chat.Room'),
            preserve_default=False,
        ),
    ]
