# Generated by Django 3.0.5 on 2020-04-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200425_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
