# Generated by Django 3.0.5 on 2020-04-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_player_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player_count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
