# Generated by Django 3.0.5 on 2020-05-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200502_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='coins',
            field=models.IntegerField(default=10),
        ),
    ]
