# Generated by Django 3.0.5 on 2020-06-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20200611_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='game_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vote',
            name='game_round',
            field=models.IntegerField(default=1),
        ),
    ]
