# Generated by Django 3.0.5 on 2020-06-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_player_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='immunity',
            field=models.BooleanField(default=False),
        ),
    ]
