# Generated by Django 3.0.5 on 2020-06-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_player_immunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
    ]
