# Generated by Django 3.0.5 on 2020-07-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_vote_is_immunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_vote_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='see_messages_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='voted_for_you_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='coins',
            field=models.IntegerField(default=5),
        ),
    ]
