# Generated by Django 3.0.5 on 2020-07-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20200703_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='anonymous_price',
            field=models.IntegerField(default=0),
        ),
    ]
