# Generated by Django 3.0.5 on 2020-07-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_player_anonymous_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bank',
            field=models.IntegerField(default=0),
        ),
    ]
