# Generated by Django 3.0.5 on 2020-07-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_room_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='objective',
            field=models.CharField(default='Pass', max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='player_objectove',
            field=models.CharField(default='', max_length=30),
        ),
    ]
