# Generated by Django 3.0.5 on 2020-07-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_auto_20200718_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_objectove',
            new_name='player_objective',
        ),
    ]
