# Generated by Django 3.0.5 on 2020-07-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_auto_20200718_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='objecttive_state',
            field=models.IntegerField(default=0),
        ),
    ]
