# Generated by Django 3.0.5 on 2020-07-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_auto_20200719_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='coin_loss_distribution',
            field=models.IntegerField(default=0),
        ),
    ]
