# Generated by Django 3.0.5 on 2020-07-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_player_coin_loss_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='num_voted_for',
            field=models.IntegerField(default=0),
        ),
    ]
